### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by vudaltsov** [mark-gerarts/automapper-plus-bundle#10]
High! It would be nice to make a release with a new config feature.

**Comment by mark-gerarts** [comment]
Hi, I drafted a new release (1.1.1). Please note that it is still a WIP and as of now only 1 option is available (create unregistered mappings). I've done some work on a separate branch that allow for some more options. If you need something specific let me know, then I'll give this some more priority.

**Comment by vudaltsov** [comment]
Thank you! That's currently enough for me, feel free to close the issue.
