### ISSUE TITLE
Update for Symfony 5

### ISSUE THREAD

**Issue by ChristianRiesen** [mark-gerarts/automapper-plus-bundle#13]
Hello. Can you allow your bundle to also install on Symfony 5? Thank you very much in advance.

**Comment by ChristianRiesen** [comment]
Created https://github.com/mark-gerarts/automapper-plus-bundle/pull/14 which should fix it @mark-gerarts

**Comment by mark-gerarts** [comment]
Thanks again! The new release is tagged 1.2.1.
