### ISSUE TITLE
Missing return type definition

### ISSUE THREAD

**Issue by tarlepp** [mark-gerarts/automapper-plus-bundle#22]
With Symfony 6.0.x (and most likely with Symfont 5.4.x) I'll see following deprecation error on Symfony profiler:

```
Method "Symfony\Component\Config\Definition\ConfigurationInterface::getConfigTreeBuilder()" might add "TreeBuilder" as a native return type declaration in the future. Do the same in implementation "AutoMapperPlus\AutoMapperPlusBundle\DependencyInjection\Configuration" now to avoid errors or add an explicit @return annotation to suppress this message.
```

**Comment by mark-gerarts** [comment]
I see you're working on a fix yourself, so I'll wait for that. Otherwise let me know and I'll take a look at it myself!

**Comment by tarlepp** [comment]
> I see you're working on a fix yourself, so I'll wait for that. Otherwise let me know and I'll take a look at it myself!

Hahhaa, I forgot to make that PR, thanks for remimder :D

**Comment by mark-gerarts** [comment]
Haha nice, thanks for the PR! Gonna wrap it up in #23
