### ISSUE TITLE
Fix deprecation message by adding void return type to AutoMapperPlusBundle::build()

### ISSUE THREAD

**Issue by developermarshak** [mark-gerarts/automapper-plus-bundle#28]
A deprecation warning in AutoMapperPlusBundle suggests adding a void return type to the build() method to align with future Symfony standards.

Message: 
`User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "AutoMapperPlus\AutoMapperPlusBundle\AutoMapperPlusBundle" now to avoid errors or add an explicit @return annotation to suppress this message.`

**Suggested Fix:**
Update AutoMapperPlusBundle::build() to include a void return type:

./AutoMapperPlusBundle.php:
```
public function build(ContainerBuilder $container): void {
    // Implementation remains unchanged
}
```

**Comment by developermarshak** [comment]
I've submitted MR   https://github.com/mark-gerarts/automapper-plus-bundle/pull/29 
Could you please review and merge if everything looks good? Thanks for your time and help!

**Comment by mark-gerarts** [comment]
Hi @developermarshak, it's the other way around: thank _you_ for your time and help.

We missed this in the Symfony 7 update. I'll merge this and tag a new version. Thanks!
