### ISSUE TITLE
Not mapping proxy classes

### ISSUE THREAD

**Issue by yhnehc** [mark-gerarts/automapper-plus-bundle#3]
When you do lazy loading sometimes the objects come back as a proxy class which breaks since there's no mapping config registered for the proxy classes.

Example of the error:
No mapping registered for converting an instance of class Proxies\\__CG__\\Bundle\\Entity\\ProductItem into one of \\ProductItemDto

**Comment by mark-gerarts** [comment]
See discussion over at https://github.com/mark-gerarts/automapper-plus/issues/9.

**Comment by segidev** [comment]
We have resolved the issue by extending the **PropertyAccessor** and overwrite the **getProperty** method.

```php
use AutoMapperPlus\PropertyAccessor\PropertyAccessor;
use Doctrine\ORM\Proxy\Proxy;

class CustomDoctrineProxyPropertyAccessor extends PropertyAccessor
{
    public function getProperty($object, string $propertyName)
    {
        // This is the magical part :)
        if ($object instanceof Proxy) {
            $object->__load();
        }

        return parent::getProperty($object, $propertyName);
    }
}
```

And then by implementing the **AutoMapperConfiguratorInterface** and overwrite the **configure** method

```php
use AutoMapperPlus\AutoMapperPlusBundle\AutoMapperConfiguratorInterface;
use AutoMapperPlus\Configuration\AutoMapperConfigInterface;

class CustomAutoMapperConfigurator implements AutoMapperConfiguratorInterface
{
    // ...
    public function configure(AutoMapperConfigInterface $config): void
    {
        // This call is important
        $config->getOptions()->setPropertyAccessor(new CustomDoctrineProxyPropertyAccessor());
    }
}
```

Each of our map class extends the **CustomAutoMapperConfigurator** class eg.

```php
class SomeAssociationMap extends CustomAutoMapperConfigurator
{
    public function configure(AutoMapperConfigInterface $config): void
    {
        $config->registerMapping(Association::class, SomeAssociationModel::class)
            ->forMember('prop', Operation::mapTo(SomeOtherClass::class));
    }
}
```
That works and we are now automatically loading proxies if they are of that type. The check if the proxy was already intialized prevents extensive reloading of the proxy.

**Comment by mark-gerarts** [comment]
Hi @segidev, thanks for providing your workaround! Just  wondering, what version of the base library (`mark-gerarts/auto-mapper-plus`) are you using? I thought this was resolved in version 1.2.2. So if you are using this version and are still getting errors I might have to reopen the [related issue](https://github.com/mark-gerarts/automapper-plus/issues/9).

**Comment by segidev** [comment]
I am out of work now and can’t tell at that moment. Although i think i saw different versions ranging from 1.1.0 to 1.2.3

The thing is i tried to update the dependency for the auto-mapper-bundle for symfony with dependencies and there was no update scheduled. So probably the issue still exists. But i will let you know on monday.

We are using Symfony 3 if that is somehow important :)

**Comment by segidev** [comment]
For several reasons that have nothing to do with this bundle we stopped implementing the library so i can’t invest further here. You can close this thread. I just wanted you to know :)

Thank you !

**Comment by mark-gerarts** [comment]
Thanks for letting me know :)
