### ISSUE TITLE
update automapper-plus  ?

### ISSUE THREAD

**Issue by michel-maier** [mark-gerarts/automapper-plus-bundle#8]
Dear  Mark,
can you create a new release to update automapper-plus-bundle and automapper-plus in order to benefit last developments?
Particularly this pull request :
https://github.com/mark-gerarts/automapper-plus/pull/39/files

BR
;-)

**Comment by mark-gerarts** [comment]
Hey @michel-maier, no problem! I've released version 1.3.6 of the library. Since this bundle requires 1.x of the library, no separate release of the bundle is needed.
